spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://nbzgxmdpjelwpx:0074d7cf8ae1bc5db9f9062d709a77355400fc2074830441b1263f04e7d0cdcc@ec2-44-196-68-164.compute-1.amazonaws.com:5432/d4pri8dmqidkut
    username: nbzgxmdpjelwpx
    password: 0074d7cf8ae1bc5db9f9062d709a77355400fc2074830441b1263f04e7d0cdcc

server:
  port: 8080

app:
  execute:
    user: 福田
  google:
    oauth2-url: https://www.googleapis.com/oauth2/v4/token
    api-url: https://sheets.googleapis.com/v4/spreadsheets/
    sheet-id: 13RqLVAYKnbff6f5cWPzqyh-1y5j8NC_brqI_Le73qhI
    client-id: 455165694555-gekiq4j8upinbq5kejusq7t92r7t560v.apps.googleusercontent.com
    client-secret: 6r7S3FqjssNuXM8FbKa-GLX0
    refresh-token: 1//0eUMWJyOCHBimCgYIARAAGA4SNwF-L9IrbwgtJYYyS1qfAi-0l2d_LjZaK1Cth6FbicCFBEeoJjc8rVdHHM5sye1xQDDuv7KHDic